services:
  - type: web
    name: welkin-backend
    env: node
    plan: free
    branch: Update_v0.1
    buildCommand: pnpm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: ~18
